import type { CVTemplate, TemplateId } from "./types";

export const TEMPLATES: CVTemplate[] = [
  {
    id: "ats-01",
    category: "ats",
    name: "Classic",
    nameId: "Klasik",
    layout: "single",
    supportsPhoto: true,
    photoPreferred: false,
    onePage: true,
    sectionOrder: [
      "profile",
      "experience",
      "education",
      "skills",
      "organizations",
      "certificates",
      "projects",
      "languages",
      "achievements",
    ],
    theme: {
      accent: "#111111",
      accentSoft: "#F3F3F3",
      ink: "#111111",
      muted: "#444444",
      paper: "#FFFFFF",
      sidebar: "#111111",
      sidebarText: "#FFFFFF",
      heading: "#111111",
      font: "serif",
      header: "centered",
      nameSize: 28,
      compact: false,
    },
    blurbId: "Hitam-putih, heading standar, mudah dipindai ATS.",
    blurbEn: "Black and white, standard headings, easy for ATS to parse.",
  },
  {
    id: "ats-02",
    category: "ats",
    name: "Modern",
    nameId: "Modern",
    layout: "single",
    supportsPhoto: true,
    photoPreferred: false,
    onePage: true,
    sectionOrder: [
      "profile",
      "experience",
      "education",
      "skills",
      "projects",
      "certificates",
      "organizations",
      "languages",
      "achievements",
    ],
    theme: {
      accent: "#1D4ED8",
      accentSoft: "#E8EEFA",
      ink: "#1A1C1E",
      muted: "#5C6570",
      paper: "#FFFFFF",
      sidebar: "#1D4ED8",
      sidebarText: "#FFFFFF",
      heading: "#1D4ED8",
      font: "sans",
      header: "left",
      nameSize: 30,
      compact: false,
    },
    blurbId: "Header modern dengan aksen biru yang tertahan.",
    blurbEn: "Modern header with a restrained blue accent.",
  },
  {
    id: "ats-03",
    category: "ats",
    name: "Executive",
    nameId: "Eksekutif",
    layout: "single",
    supportsPhoto: true,
    photoPreferred: false,
    onePage: true,
    sectionOrder: [
      "profile",
      "experience",
      "education",
      "skills",
      "achievements",
      "certificates",
      "organizations",
      "projects",
      "languages",
    ],
    theme: {
      accent: "#0F2744",
      accentSoft: "#EEF2F6",
      ink: "#0F2744",
      muted: "#5C6570",
      paper: "#FFFFFF",
      sidebar: "#0F2744",
      sidebarText: "#F6F3EE",
      heading: "#0F2744",
      font: "mixed",
      header: "split",
      nameSize: 32,
      compact: false,
    },
    blurbId: "Nama kuat, highlight karier, kesan formal.",
    blurbEn: "Strong name, career highlights, formal presence.",
  },
  {
    id: "ats-04",
    category: "ats",
    name: "Fresh Graduate",
    nameId: "Fresh Graduate",
    layout: "single",
    supportsPhoto: true,
    photoPreferred: false,
    onePage: true,
    sectionOrder: [
      "profile",
      "education",
      "projects",
      "organizations",
      "experience",
      "skills",
      "certificates",
      "achievements",
      "languages",
    ],
    theme: {
      accent: "#0F5F8A",
      accentSoft: "#E7F2F8",
      ink: "#1A1C1E",
      muted: "#5C6570",
      paper: "#FFFFFF",
      sidebar: "#0F5F8A",
      sidebarText: "#FFFFFF",
      heading: "#0F5F8A",
      font: "sans",
      header: "left",
      nameSize: 28,
      compact: false,
    },
    blurbId: "Pendidikan, proyek, dan organisasi lebih menonjol.",
    blurbEn: "Education, projects, and organizations take the lead.",
  },
  {
    id: "ats-05",
    category: "ats",
    name: "Compact",
    nameId: "Ringkas",
    layout: "single",
    supportsPhoto: true,
    photoPreferred: false,
    onePage: true,
    sectionOrder: [
      "profile",
      "experience",
      "education",
      "skills",
      "projects",
      "certificates",
      "organizations",
      "languages",
      "achievements",
    ],
    theme: {
      accent: "#1A1C1E",
      accentSoft: "#F1EFEA",
      ink: "#1A1C1E",
      muted: "#5C6570",
      paper: "#FFFFFF",
      sidebar: "#1A1C1E",
      sidebarText: "#FFFFFF",
      heading: "#1A1C1E",
      font: "sans",
      header: "left",
      nameSize: 24,
      compact: true,
    },
    blurbId: "Tipografi rapat, efisien untuk banyak konten.",
    blurbEn: "Tight type, efficient when you have a lot to say.",
  },
  {
    id: "cr-01",
    category: "creative",
    name: "Sidebar",
    nameId: "Sidebar",
    layout: "sidebar",
    supportsPhoto: true,
    photoPreferred: true,
    onePage: true,
    sectionOrder: [
      "profile",
      "experience",
      "education",
      "projects",
      "certificates",
      "organizations",
      "achievements",
      "skills",
      "languages",
    ],
    theme: {
      accent: "#0F2744",
      accentSoft: "#E8EEF4",
      ink: "#1A1C1E",
      muted: "#5C6570",
      paper: "#FFFFFF",
      sidebar: "#0F2744",
      sidebarText: "#F4F1EA",
      heading: "#0F2744",
      font: "sans",
      header: "left",
      nameSize: 26,
      compact: false,
    },
    blurbId: "Kolom kiri untuk foto, kontak, dan keahlian.",
    blurbEn: "Left column for photo, contact, and skills.",
  },
  {
    id: "cr-02",
    category: "creative",
    name: "Timeline",
    nameId: "Linimasa",
    layout: "timeline",
    supportsPhoto: true,
    photoPreferred: false,
    onePage: true,
    sectionOrder: [
      "profile",
      "experience",
      "education",
      "skills",
      "projects",
      "certificates",
      "organizations",
      "languages",
      "achievements",
    ],
    theme: {
      accent: "#1D6A7A",
      accentSoft: "#E4F2F4",
      ink: "#1A1C1E",
      muted: "#5C6570",
      paper: "#FFFFFF",
      sidebar: "#1D6A7A",
      sidebarText: "#FFFFFF",
      heading: "#1D6A7A",
      font: "sans",
      header: "left",
      nameSize: 28,
      compact: false,
    },
    blurbId: "Pengalaman dan pendidikan dalam garis waktu.",
    blurbEn: "Experience and education along a timeline.",
  },
  {
    id: "cr-03",
    category: "creative",
    name: "Personal Branding",
    nameId: "Personal Branding",
    layout: "branding",
    supportsPhoto: true,
    photoPreferred: true,
    onePage: true,
    sectionOrder: [
      "profile",
      "experience",
      "projects",
      "education",
      "skills",
      "certificates",
      "organizations",
      "achievements",
      "languages",
    ],
    theme: {
      accent: "#1D4ED8",
      accentSoft: "#E8EEFA",
      ink: "#0F2744",
      muted: "#5C6570",
      paper: "#FFFFFF",
      sidebar: "#1D4ED8",
      sidebarText: "#FFFFFF",
      heading: "#1D4ED8",
      font: "mixed",
      header: "split",
      nameSize: 36,
      compact: false,
    },
    blurbId: "Nama besar, kesan portofolio, foto menonjol.",
    blurbEn: "Large name, portfolio feel, prominent photo.",
  },
  {
    id: "cr-04",
    category: "creative",
    name: "Elegant",
    nameId: "Elegan",
    layout: "split",
    supportsPhoto: true,
    photoPreferred: false,
    onePage: true,
    sectionOrder: [
      "profile",
      "experience",
      "education",
      "projects",
      "skills",
      "certificates",
      "organizations",
      "languages",
      "achievements",
    ],
    theme: {
      accent: "#3D4C5C",
      accentSoft: "#F1EFEA",
      ink: "#2A3038",
      muted: "#6B7380",
      paper: "#FFFcf8",
      sidebar: "#F1EFEA",
      sidebarText: "#2A3038",
      heading: "#3D4C5C",
      font: "serif",
      header: "centered",
      nameSize: 30,
      compact: false,
    },
    blurbId: "Ruang putih, tipografi halus, warna tertahan.",
    blurbEn: "White space, refined type, restrained color.",
  },
  {
    id: "cr-05",
    category: "creative",
    name: "Bold",
    nameId: "Tegas",
    layout: "bold",
    supportsPhoto: true,
    photoPreferred: true,
    onePage: true,
    sectionOrder: [
      "profile",
      "experience",
      "education",
      "skills",
      "projects",
      "certificates",
      "organizations",
      "achievements",
      "languages",
    ],
    theme: {
      accent: "#0F2744",
      accentSoft: "#E6EBF1",
      ink: "#1A1C1E",
      muted: "#5C6570",
      paper: "#FFFFFF",
      sidebar: "#0F2744",
      sidebarText: "#F6F3EE",
      heading: "#0F2744",
      font: "sans",
      header: "band",
      nameSize: 30,
      compact: false,
    },
    blurbId: "Pita header kuat dan hierarki visual tegas.",
    blurbEn: "Strong header band and a bold visual hierarchy.",
  },
];

export function getTemplate(id: TemplateId): CVTemplate {
  return TEMPLATES.find((t) => t.id === id) ?? TEMPLATES[0];
}

export function templatesByCategory(category: "ats" | "creative") {
  return TEMPLATES.filter((t) => t.category === category);
}
